name: "Test docker-compose-web-modeler.yaml"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    uses: ./.github/workflows/template-deploy.yaml
    secrets: inherit
    with:
      compose_args: "-f docker-compose.yaml -f docker-compose-web-modeler.yaml"
      run_e2e_tests: true
  e2e_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./e2e_tests

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e_tests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./e2e_tests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: e2e_tests/playwright-report/
          retention-days: 30

