name: "Test docker-compose-web-modeler.yaml"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    uses: ./.github/workflows/template-deploy.yaml
    with:
      compose_args: "-f docker-compose.yaml -f docker-compose-web-modeler.yaml"

